### ISSUE TITLE
Refactor the readme and create a wiki page

### ISSUE THREAD

**Issue by jwhchambers** [codingforeveryone/codingforeveryone.github.io#10]

**Comment by samhstn** [comment]
## How the README might look:

 --- gitter badge ---

View the current site here: "Link to site"

#### What

What is this repo about

#### Why

Why are we building it

#### How

How we are going to build it

Links to the wiki for:
- Issues
- How to getting started with development
- File structure
- How to contribute
- Developer rules and guidelines

**Comment by pjcevans** [comment]
I've initialised the [wiki](https://github.com/codingforeveryone/codingforeveryone.github.io/wiki), that should make it quicker to transfer some of this out of the README

**Comment by samhstn** [comment]
Nice work @pjcevans, the wiki looks good, it will become clear what should go in there as we develop.

**Comment by jwhchambers** [comment]
Cheers on the wiki @pjcevans , I think with the wiki and readme now set up we can close this too
