### ISSUE TITLE
Info: We'll be using the Founders and Coders github issue workflow

### ISSUE THREAD

**Issue by pjcevans** [codingforeveryone/codingforeveryone.github.io#16]
Here's a link to get some inspiration:

https://github.com/foundersandcoders/oursite/issues

I believe the idea is that whenever a pull request is merged there should be at least one issue that is solved by merging the PR, and if there is not then one should be created.

**Comment by samhstn** [comment]
Great, I think this information should go in the development guidelines/rules in the wiki

**Comment by pjcevans** [comment]
added to the [wiki](https://github.com/codingforeveryone/codingforeveryone.github.io/wiki/Developer-Rules-and-Guidelines) so closing the issue
